export { default as Header } from './Header/Header.jsx'
export { default as Timeline } from './Timeline/Timeline.jsx'
export { default as TimelineItem } from './TimelineItem/TimelineItem.jsx'
export { default as Companies } from './Companies/Companies.jsx'
export { default as SectionTitle } from './SectionTitle/SectionTitle.jsx'
export { default as Footer } from './Footer/Footer.jsx'
